from abc import ABC, abstractmethod
from typing import AsyncIterator
from cloudbridge.events import _Event

class SessionDriver(ABC):
    @abstractmethod
    async def start(self) -> None: ...
    @abstractmethod
    async def send(self, text: str) -> None: ...
    @abstractmethod
    async def answer_permission(self, request_id: str, allow: bool) -> None: ...
    @abstractmethod
    def events(self) -> AsyncIterator[_Event]: ...
    @abstractmethod
    async def close(self) -> None: ...
